### ISSUE TITLE
When adding/editing a link HTTP POST/PUT should be used

### ISSUE THREAD

**Issue by wwsean08** [F5Networks/f5go#5]
The way f5go is imlemented it currently uses GET for everything including updating records.  While not an issue it is something that shouldn't be done, here's my logs showing a link being added via GET.

::ffff:10.0.0.10 - - [10/Jun/2016:23:53:25] "**GET** /_add_?title=&url=&otherlists=http%3A%2F%2F10.0.0.99%3A5000%2F&lists=nas&returnto=nas&error=URL+required HTTP/1.1" 500 1493 "http://go/_add_/nas" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
::ffff:10.0.0.10 - - [10/Jun/2016:23:53:25] "GET /favicon.ico HTTP/1.1" 301 - "http://go/_add_?title=&url=&otherlists=http%3A%2F%2F10.0.0.99%3A5000%2F&lists=nas&returnto=nas&error=URL+required" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

**Comment by moronbros** [comment]
I think switching to a POST here would be correct. It's the correct HTTP verb in this situation.
