### ISSUE TITLE
Delete in edit pane unintuitive

### ISSUE THREAD

**Issue by wwsean08** [F5Networks/f5go#9]
When deleting a link in the edit pane that has multiple keywords you can unintentionally delete multiple keywords if you don't know what you are doing.

If you hit delete on this one, all keywords shown would get deleted.

![capture](https://cloud.githubusercontent.com/assets/839261/16244167/9c64f774-37af-11e6-9960-13d0560acb64.PNG)

**Comment by wwsean08** [comment]
While it's not the best solution (though probably something that should exist anyways), I have staged some javascript to confirm that the user wants to delete the links before actually deleting them.  @moronbros if you have any feedback on this change let me know.

![capture](https://cloud.githubusercontent.com/assets/839261/16360814/273006cc-3b2b-11e6-9ca4-99d6e487dad3.PNG)

**Comment by moronbros** [comment]
ship it!
